name: Bingo
version: '${project.version}'
main: de.amin.bingo.BingoPlugin
authors: [ Duckulus ]
description: Bingo
api-version: 1.13
commands:
  forcestart:
    aliases:
      - fs
    permission: bingo.fs
    description: Force Starts the Game if possible
  board:
    aliases:
      - cboard
      - seeboard
    description: Lets you view your BingoBoard
  reroll:
    aliases:
      - rr
    description: rerolls all boards
    permission: bingo.reroll
  backpack:
    aliases:
      - bp
    description: opens the teams backpack
